"""Preprocessing rule for Razor/Blazor files.

Generates an .editorconfig template and RazorAssemblyInfo.cs for use
with the Razor source generator in csharp_library / csharp_binary.
"""

RazorFilesInfo = provider(
    doc = "Information about preprocessed Razor files for consumption by csharp_* rules.",
    fields = {
        "razor_files": "depset[File]: The .razor and .cshtml source files",
        "analyzer_config_template": "File: The generated .editorconfig template (paths resolved at execution time)",
        "assembly_info": "File: Generated RazorAssemblyInfo.cs",
    },
)

def _razor_preprocess_impl(ctx):
    razor_files = ctx.files.srcs
    if not razor_files:
        fail("razor_preprocess requires at least one .razor or .cshtml file in srcs")

    # Generate the editorconfig template.
    # Section headers use sentinel values that compiler_wrapper.sh will
    # replace with absolute sandbox paths at execution time.
    editorconfig = ctx.actions.declare_file(ctx.attr.name + ".GeneratedRazorEditorConfig.editorconfig")

    lines = ["is_global = true", ""]
    for f in razor_files:
        # Write the file path as a sentinel. The compiler wrapper will
        # rewrite [__RAZOR_FILE__:path] to [<absolute_sandbox_path>].
        lines.append("[__RAZOR_FILE__:%s]" % f.path)
        lines.append("build_metadata.AdditionalFiles.TargetPath = __RAZOR_B64__:%s" % f.short_path)
        lines.append("build_metadata.AdditionalFiles.CssScope =")
        lines.append("")

    ctx.actions.write(editorconfig, "\n".join(lines))

    # Generate RazorAssemblyInfo.cs with required assembly-level attribute.
    assembly_info = ctx.actions.declare_file(ctx.attr.name + ".RazorAssemblyInfo.cs")
    assembly_info_content = "\n".join([
        "// <auto-generated/>",
        "using System.Reflection;",
        "",
        "[assembly: Microsoft.AspNetCore.Mvc.ApplicationParts.ProvideApplicationPartFactoryAttribute(" +
        "\"Microsoft.AspNetCore.Mvc.ApplicationParts.CompiledRazorAssemblyApplicationPartFactory, " +
        "Microsoft.AspNetCore.Mvc.Razor\")]",
        "",
    ])
    ctx.actions.write(assembly_info, assembly_info_content)

    return [
        RazorFilesInfo(
            razor_files = depset(razor_files),
            analyzer_config_template = editorconfig,
            assembly_info = assembly_info,
        ),
        DefaultInfo(files = depset([editorconfig, assembly_info])),
    ]

razor_preprocess = rule(
    _razor_preprocess_impl,
    doc = "Preprocess Razor/Blazor files for use with csharp_library/csharp_binary.",
    attrs = {
        "srcs": attr.label_list(
            doc = "Razor (.razor) and cshtml (.cshtml) source files.",
            allow_files = [".razor", ".cshtml"],
            mandatory = True,
            allow_empty = False,
        ),
    },
)
