"""Convenience macro for building Razor/Blazor libraries.

This macro wraps genrule (for preprocessing) + csharp_library, following
the same pattern as csharp_nunit_test wrapping csharp_test.
"""

load("//dotnet/private/rules/csharp:library.bzl", "csharp_library")

def razor_library(
        name,
        razor_srcs,
        srcs = [],
        deps = [],
        target_frameworks = [],
        project_sdk = "web",
        nullable = "enable",
        **kwargs):
    """Build a C# library that includes Razor/Blazor files.

    This macro creates preprocessing targets for .razor/.cshtml files
    and a csharp_library that consumes them via the Razor source generator
    pipeline. The source generator reads .razor/.cshtml files from
    /additionalfile: arguments and the generated editorconfig provides
    per-file metadata with absolute sandbox paths.

    Users must include the Razor source generator NuGet package in deps
    (e.g., @nuget//microsoft.net.sdk.razor.sourcegenerators).

    Args:
        name: Target name.
        razor_srcs: List of .razor and .cshtml files.
        srcs: List of .cs source files.
        deps: Dependencies.
        target_frameworks: Target framework monikers.
        project_sdk: Project SDK (defaults to "web").
        nullable: Nullable context setting (defaults to "enable").
        **kwargs: Additional arguments passed to csharp_library.
    """
    assembly_info_name = name + "_razor_assembly_info"
    editorconfig_name = name + "_razor_editorconfig"

    # Generate RazorAssemblyInfo.cs with required assembly-level attribute
    native.genrule(
        name = assembly_info_name,
        outs = [assembly_info_name + ".cs"],
        cmd = "cat > $@ <<'ENDOFFILE'\n" +
              "// <auto-generated/>\n" +
              "using System.Reflection;\n" +
              "\n" +
              "[assembly: Microsoft.AspNetCore.Mvc.ApplicationParts.ProvideApplicationPartFactoryAttribute(" +
              "\"Microsoft.AspNetCore.Mvc.ApplicationParts.CompiledRazorAssemblyApplicationPartFactory, " +
              "Microsoft.AspNetCore.Mvc.Razor\")]\n" +
              "ENDOFFILE",
    )

    # Generate the editorconfig template with sentinel values.
    # The compiler_wrapper.sh will replace __RAZOR_FILE__: with $PWD/
    # and __RAZOR_B64__: with base64-encoded target paths at execution time.
    editorconfig_lines = ["is_global = true", ""]
    for src in razor_srcs:
        # Normalize the label to a path for the sentinel
        src_path = src
        if src_path.startswith(":"):
            src_path = src_path[1:]
        elif src_path.startswith("//"):
            # Extract the path part after the package
            src_path = src_path.split(":")[-1] if ":" in src_path else src_path.split("/")[-1]
        editorconfig_lines.append("[__RAZOR_FILE__:%s]" % src_path)
        editorconfig_lines.append("build_metadata.AdditionalFiles.TargetPath = __RAZOR_B64__:%s" % src_path)
        editorconfig_lines.append("build_metadata.AdditionalFiles.CssScope =")
        editorconfig_lines.append("")

    editorconfig_content = "\n".join(editorconfig_lines)
    native.genrule(
        name = editorconfig_name,
        outs = [editorconfig_name + ".editorconfig"],
        cmd = "cat > $@ <<'RAZOR_EDITORCONFIG_EOF'\n" + editorconfig_content + "\nRAZOR_EDITORCONFIG_EOF",
    )

    csharp_library(
        name = name,
        srcs = srcs + [assembly_info_name + ".cs"],
        additionalfiles = razor_srcs,
        analyzer_configs = [editorconfig_name + ".editorconfig"],
        deps = deps,
        target_frameworks = target_frameworks,
        project_sdk = project_sdk,
        nullable = nullable,
        **kwargs
    )
