"""
Actions for compiling targets with C#.
"""

load(
    "//dotnet/private:common.bzl",
    "FRAMEWORK_COMPATIBILITY",
    "collect_compile_info",
    "copy_files_to_dir",
    "format_ref_arg",
    "framework_preprocessor_symbols",
    "generate_warning_args",
    "get_framework_version_info",
    "map_resource_arg",
    "use_highentropyva",
)
load(
    "//dotnet/private:providers.bzl",
    "DotnetAssemblyCompileInfo",
    "DotnetAssemblyRuntimeInfo",
)

# #436 — Implicit usings by SDK, matching MSBuild behavior.
# See: https://github.com/dotnet/sdk/blob/main/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.CSharp.props
_IMPLICIT_USINGS_DEFAULT = [
    "System",
    "System.Collections.Generic",
    "System.IO",
    "System.Linq",
    "System.Net.Http",
    "System.Threading",
    "System.Threading.Tasks",
]

# See: https://github.com/dotnet/sdk/blob/main/src/WebSdk/Web/Targets/Sdk.Server.props
_IMPLICIT_USINGS_WEB = _IMPLICIT_USINGS_DEFAULT + [
    "System.Net.Http.Json",
    "Microsoft.AspNetCore.Builder",
    "Microsoft.AspNetCore.Hosting",
    "Microsoft.AspNetCore.Http",
    "Microsoft.AspNetCore.Routing",
    "Microsoft.Extensions.Configuration",
    "Microsoft.Extensions.DependencyInjection",
    "Microsoft.Extensions.Hosting",
    "Microsoft.Extensions.Logging",
]

_IMPLICIT_USINGS_BY_SDK = {
    "default": _IMPLICIT_USINGS_DEFAULT,
    "web": _IMPLICIT_USINGS_WEB,
}

# Implicit usings were introduced in .NET 6.0
_IMPLICIT_USINGS_MIN_TFM = "net6.0"

def _should_generate_implicit_usings(target_framework, implicit_usings):
    """Returns True if implicit usings should be generated for this TFM."""
    if not implicit_usings:
        return False
    keys = list(FRAMEWORK_COMPATIBILITY.keys())
    if target_framework not in keys:
        return False
    if _IMPLICIT_USINGS_MIN_TFM not in keys:
        return False
    min_index = keys.index(_IMPLICIT_USINGS_MIN_TFM)
    tfm_index = keys.index(target_framework)
    return tfm_index >= min_index

def _generate_global_usings_file(actions, target_name, assembly_name, project_sdk, target_framework):
    """Generate a GlobalUsings.g.cs file with implicit using directives.

    Args:
        actions: ctx.actions module.
        target_name: The target name (for output path).
        assembly_name: The assembly name.
        project_sdk: The project SDK ("default" or "web").
        target_framework: The target framework moniker.

    Returns:
        A File for the generated GlobalUsings.g.cs.
    """
    namespaces = _IMPLICIT_USINGS_BY_SDK.get(project_sdk, _IMPLICIT_USINGS_DEFAULT)

    lines = ["// <auto-generated/>"]
    for ns in namespaces:
        lines.append("global using global::%s;" % ns)

    content = "\n".join(lines) + "\n"

    output = actions.declare_file(
        "%s/%s/%s.GlobalUsings.g.cs" % (target_name, target_framework, assembly_name),
    )
    actions.write(output, content)
    return output

def _write_internals_visible_to_csharp(actions, label_name, dll_name, others):
    """Write a .cs file containing InternalsVisibleTo attributes.

    Letting Bazel see which assemblies we are going to have InternalsVisibleTo
    allows for more robust caching of compiles.

    Args:
      actions: An actions module, usually from ctx.actions.
      label_name: The label name.
      dll_name: The assembly name.
      others: The names of other assemblies.

    Returns:
      A File object for a generated .cs file
    """

    if len(others) == 0:
        return None

    attrs = actions.args()
    attrs.set_param_file_format(format = "multiline")

    attrs.add_all(
        others,
        format_each = "[assembly: System.Runtime.CompilerServices.InternalsVisibleTo(\"%s\")]",
    )

    output = actions.declare_file("%s/%s/internalsvisibleto.cs" % (label_name, dll_name))

    actions.write(output, attrs)

    return output

def _write_version_csharp(actions, label_name, dll_name, version):
    """Write a .cs file containing assembly version attributes.

    Args:
      actions: An actions module, usually from ctx.actions.
      label_name: The label name.
      dll_name: The assembly name.
      version: The version string.

    Returns:
      A File object for a generated .cs file, or None if version is empty.
    """
    if not version:
        return None

    content = (
        '[assembly: System.Reflection.AssemblyVersion("{v}")]\n' +
        '[assembly: System.Reflection.AssemblyFileVersion("{v}")]\n' +
        '[assembly: System.Reflection.AssemblyInformationalVersion("{v}")]\n'
    ).format(v = version)

    output = actions.declare_file("%s/%s/assemblyversion.cs" % (label_name, dll_name))
    actions.write(output, content)

    return output

def _collect_analyzer_dependencies(deps):
    """Collect the runtime libraries of this analyzer. These will be passed to the compiler.

    Only direct dependency libs are included. strict_deps does not apply here:
    strict_deps controls which compile-time references the *compiled code* can
    see, whereas these are runtime libraries the *analyzer itself* needs to load
    inside the compiler process. Transitive resolution is handled by Bazel's
    dependency graph — each dep already carries its own transitive closure.

    Args:
        deps: The list of dependencies of the analyzer.

    Returns:
        The list of analyzer dependencies.
    """

    dlls = []
    for dep in deps:
        runtime_info = dep[DotnetAssemblyRuntimeInfo]
        dlls.extend(runtime_info.libs)
    return dlls

# buildifier: disable=unnamed-macro
def AssemblyAction(
        actions,
        compiler_wrapper,
        label,
        additionalfiles,
        debug,
        defines,
        deps,
        exports,
        targeting_pack,
        internals_visible_to,
        keyfile,
        langversion,
        resources,
        srcs,
        data,
        appsetting_files,
        compile_data,
        out,
        # #423
        version,
        target,
        target_name,
        target_framework,
        toolchain,
        strict_deps,
        generate_documentation_file,
        include_host_model_dll,
        treat_warnings_as_errors,
        warnings_as_errors,
        warnings_not_as_errors,
        warning_level,
        nowarn,
        project_sdk,
        allow_unsafe_blocks,
        nullable,
        run_analyzers,
        is_analyzer,
        is_language_specific_analyzer,
        analyzer_configs,
        compiler_options,
        pathmap,
        is_windows,
        # #436
        implicit_usings = True,
        # #349
        native = [],
        # Extra analyzer files from global config
        extra_analyzer_files = None):
    """Creates an action that runs the CSharp compiler with the specified inputs.

    This macro aims to match the [C# compiler](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/listed-alphabetically), with the inputs mapping to compiler options.

    Args:
        actions: Bazel module providing functions to create actions.
        compiler_wrapper: The wrapper script that invokes the C# compiler.
        label: The label of the target. This is used to determine the relative path of embedded resources.
        additionalfiles: Names additional files that don't directly affect code generation but may be used by analyzers for producing errors or warnings.
        debug: Emits debugging information.
        defines: The list of conditional compilation symbols.
        deps: The list of other libraries to be linked in to the assembly.
        exports: List of exported targets.
        targeting_pack: The targeting pack being used.
        internals_visible_to: An optional list of assemblies that can see this assemblies internal symbols.
        keyfile: Specifies a strong name key file of the assembly.
        langversion: Specify language version: Default, ISO-1, ISO-2, 3, 4, 5, 6, 7, 7.1, 7.2, 7.3, or Latest
        resources: The list of resouces to be embedded in the assembly.
        srcs: The list of source (.cs) files that are processed to create the assembly.
        data: List of files that are a direct runtime dependency
        appsetting_files: List of appsettings files to include in the output.
        compile_data: List of files that are a direct compile time dependency
        target_name: A unique name for this target.
        out: Specifies the output file name.
        target: Specifies the format of the output file by using one of four options.
        target_framework: The target framework moniker for the assembly.
        toolchain: The toolchain that supply the C# compiler.
        strict_deps: Whether or not to use strict dependencies.
        generate_documentation_file: Whether or not to output XML docs for the compiled dll.
        include_host_model_dll: Whether or not to include he Microsoft.NET.HostModel dll. ONLY USED FOR COMPILING THE APPHOST SHIMMER.
        treat_warnings_as_errors: Whether or not to treat warnings as errors.
        warnings_as_errors: List of warnings to treat as errors.
        warnings_not_as_errors: List of warnings to not treat errors.
        warning_level: The warning level to use.
        nowarn: List of warnings to suppress.
        project_sdk: The project sdk being targeted
        allow_unsafe_blocks: Compiles the target with /unsafe
        nullable: Enable nullable context, or nullable warnings.
        run_analyzers: Enable analyzers.
        is_analyzer: Whether or not the target is an analyzer.
        is_language_specific_analyzer: Whether or not the target is a language specific analyzer.
        analyzer_configs: List of analyzer configuration files.
        compiler_options: Additional options to pass to the compiler.
        pathmap: Dictionary of source path remappings for PDB debugger support.
        is_windows: Whether or not the target is running on Windows.
        implicit_usings: Whether to generate implicit global using directives for net6.0+.
        native: List of native shared library files for P/Invoke interop.
        extra_analyzer_files: depset of additional analyzer DLL files from global analysis config.
    Returns:
        The compiled csharp artifacts.
    """

    assembly_name = target_name if out == "" else out
    effective_version = version if version else "1.0.0"

    # --- Assembly version (#423) ---
    version_cs = _write_version_csharp(actions, target_name, assembly_name, version)
    if version_cs:
        srcs = srcs + [version_cs]

    # --- end assembly version: #423 ---

    # --- Implicit usings (#436) ---
    if _should_generate_implicit_usings(target_framework, implicit_usings):
        global_usings_file = _generate_global_usings_file(
            actions,
            target_name,
            assembly_name,
            project_sdk,
            target_framework,
        )
        srcs = [global_usings_file] + srcs

    # --- end implicit usings: #436 ---

    subsystem_version = get_framework_version_info(target_framework)
    (
        irefs,
        prefs,
        analyzers,
        analyzers_csharp,
        analyzers_fsharp,
        analyzers_vb,
        transitive_compile_data,
        framework_files,
        exports_files,
        dep_content_srcs,
    ) = collect_compile_info(
        assembly_name,
        deps + [toolchain.host_model] if include_host_model_dll else deps,
        targeting_pack,
        exports,
        strict_deps,
    )

    # Inject source files from source-only NuGet packages into compilation
    content_src_files = dep_content_srcs.to_list()
    if content_src_files:
        srcs = srcs + content_src_files

    # --- Append analyzers from global analysis config ---
    if extra_analyzer_files:
        analyzers = depset(transitive = [analyzers, extra_analyzer_files])

    # --- end global analyzers ---

    if (is_analyzer or is_language_specific_analyzer) and target_framework != "netstandard2.0":
        fail("Analyzers must have `target_frameworks = [\"netstandard2.0\"]`.")

    # NB: The fail() above enforces that the analyzer itself targets netstandard2.0.
    # Analyzer *dependencies* should also target netstandard2.0, but this is not
    # validated here because it would require a provider carrying each dep's TFM.
    analyzer_dlls = _collect_analyzer_dependencies(deps) if (is_analyzer or is_language_specific_analyzer) else []

    defines = framework_preprocessor_symbols(target_framework) + defines

    out_dir = target_name + "/" + target_framework
    out_ext = "dll"

    out_dll = actions.declare_file("%s/%s.%s" % (out_dir, assembly_name, out_ext))
    out_iref = None
    out_ref = actions.declare_file("%s/ref/%s.%s" % (out_dir, assembly_name, out_ext))
    out_pdb = actions.declare_file("%s/%s.pdb" % (out_dir, assembly_name))
    out_xml = actions.declare_file("%s/%s.xml" % (out_dir, assembly_name)) if generate_documentation_file else None

    # Appsettings
    out_appsettings = copy_files_to_dir(target_name, actions, is_windows, appsetting_files, out_dir)

    if len(internals_visible_to) == 0 or is_analyzer:
        _compile(
            actions,
            compiler_wrapper,
            label,
            additionalfiles,
            analyzers,
            analyzers_csharp,
            analyzer_configs,
            debug,
            defines,
            keyfile,
            langversion,
            irefs,
            framework_files,
            resources,
            srcs,
            depset(compile_data, transitive = [transitive_compile_data]),
            subsystem_version,
            target,
            target_name,
            target_framework,
            toolchain,
            treat_warnings_as_errors,
            warnings_as_errors,
            warnings_not_as_errors,
            warning_level,
            nowarn,
            allow_unsafe_blocks,
            nullable,
            run_analyzers,
            compiler_options,
            pathmap = pathmap,
            out_dll = out_dll,
            out_ref = out_ref,
            out_pdb = out_pdb,
            out_xml = out_xml,
        )
    else:
        # If the user is using internals_visible_to generate an additional
        # reference-only DLL that contains the internals. We want the
        # InternalsVisibleTo in the main DLL too to be less suprising to users.
        out_iref = actions.declare_file("%s/iref/%s.%s" % (out_dir, assembly_name, out_ext))

        internals_visible_to_cs = _write_internals_visible_to_csharp(
            actions,
            label_name = target_name,
            dll_name = assembly_name,
            others = internals_visible_to,
        )

        _compile(
            actions,
            compiler_wrapper,
            label,
            additionalfiles,
            analyzers,
            analyzers_csharp,
            analyzer_configs,
            debug,
            defines,
            keyfile,
            langversion,
            irefs,
            framework_files,
            resources,
            srcs + [internals_visible_to_cs],
            depset(compile_data, transitive = [transitive_compile_data]),
            subsystem_version,
            target,
            target_name,
            target_framework,
            toolchain,
            treat_warnings_as_errors,
            warnings_as_errors,
            warnings_not_as_errors,
            warning_level,
            nowarn,
            allow_unsafe_blocks,
            nullable,
            run_analyzers,
            compiler_options,
            pathmap = pathmap,
            out_ref = out_iref,
            out_dll = out_dll,
            out_pdb = out_pdb,
            out_xml = out_xml,
        )

        # Generate a ref-only DLL without internals
        _compile(
            actions,
            compiler_wrapper,
            label,
            additionalfiles,
            analyzers,
            analyzers_csharp,
            analyzer_configs,
            debug,
            defines,
            keyfile,
            langversion,
            irefs,
            framework_files,
            resources,
            srcs,
            depset(compile_data, transitive = [transitive_compile_data]),
            subsystem_version,
            target,
            target_name,
            target_framework,
            toolchain,
            treat_warnings_as_errors,
            warnings_as_errors,
            warnings_not_as_errors,
            warning_level,
            nowarn,
            allow_unsafe_blocks,
            nullable,
            run_analyzers,
            compiler_options,
            pathmap = pathmap,
            out_dll = None,
            out_ref = out_ref,
            out_pdb = None,
            out_xml = None,
        )

    return (DotnetAssemblyCompileInfo(
        name = assembly_name,
        version = effective_version,
        project_sdk = project_sdk,
        refs = [out_ref] if not is_analyzer else [],
        irefs = [out_iref] if out_iref else [out_ref],
        analyzers = [] if (not is_analyzer) or is_language_specific_analyzer else ([out_dll] + analyzer_dlls),
        analyzers_csharp = ([out_dll] + analyzer_dlls) if is_language_specific_analyzer else [],
        analyzers_fsharp = [],
        analyzers_vb = [],
        internals_visible_to = internals_visible_to or [],
        compile_data = compile_data,
        exports = exports_files,
        transitive_refs = prefs if not (is_analyzer or is_language_specific_analyzer) else depset(),
        transitive_analyzers = analyzers,
        transitive_analyzers_csharp = analyzers_csharp,
        transitive_analyzers_fsharp = analyzers_fsharp,
        transitive_analyzers_vb = analyzers_vb,
        transitive_compile_data = transitive_compile_data,
        content_srcs = [],
        transitive_content_srcs = dep_content_srcs,
    ), DotnetAssemblyRuntimeInfo(
        name = assembly_name,
        version = effective_version,
        libs = [out_dll] if not (is_analyzer or is_language_specific_analyzer) else [],
        resource_assemblies = [],
        pdbs = [out_pdb] if out_pdb else [],
        xml_docs = [out_xml] if out_xml else [],
        data = data,
        appsetting_files = depset(out_appsettings),
        native = native,
        deps = depset(
            [dep[DotnetAssemblyRuntimeInfo] for dep in deps] + [toolchain.host_model[DotnetAssemblyRuntimeInfo]] if include_host_model_dll else [dep[DotnetAssemblyRuntimeInfo] for dep in deps],
            transitive = [dep[DotnetAssemblyRuntimeInfo].deps for dep in deps],
        ) if not (is_analyzer or is_language_specific_analyzer) else depset(),
        nuget_info = None,
        direct_deps_depsjson_fragment = {dep[DotnetAssemblyRuntimeInfo].name: dep[DotnetAssemblyRuntimeInfo].version for dep in deps},
    ))

def _compile(
        actions,
        compiler_wrapper,
        label,
        additionalfiles,
        analyzer_assemblies,
        analyzer_assemblies_csharp,
        analyzer_configs,
        debug,
        defines,
        keyfile,
        langversion,
        refs,
        framework_files,
        resources,
        srcs,
        compile_data,
        subsystem_version,
        target,
        target_name,
        target_framework,
        toolchain,
        treat_warnings_as_errors,
        warnings_as_errors,
        warnings_not_as_errors,
        warning_level,
        nowarn,
        allow_unsafe_blocks,
        nullable,
        run_analyzers,
        compiler_options,
        pathmap = {},
        out_dll = None,
        out_ref = None,
        out_pdb = None,
        out_xml = None):
    # Our goal is to match msbuild as much as reasonable
    # https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/listed-alphabetically
    args = actions.args()
    if (allow_unsafe_blocks):
        args.add("/unsafe+")
    else:
        args.add("/unsafe-")
    args.add("/checked-")
    args.add("/nostdlib+")  # mscorlib will get added due to our transitive deps
    args.add("/utf8output")
    args.add("/deterministic+")
    args.add("/filealign:512")

    args.add("/nologo")

    if use_highentropyva(target_framework):
        args.add("/highentropyva+")
    else:
        args.add("/highentropyva-")

    if (nullable == "enable"):
        args.add("/nullable:enable")
    elif (nullable == "warnings"):
        args.add("/nullable:warnings")
    elif (nullable == "annotations"):
        args.add("/nullable:annotations")
    else:
        args.add("/nullable:disable")

    if subsystem_version != None:
        args.add("/subsystemversion:" + subsystem_version)

    generate_warning_args(
        args,
        treat_warnings_as_errors,
        warnings_as_errors,
        warnings_not_as_errors,
        warning_level,
        nowarn,
    )

    args.add("/target:" + target)
    args.add("/langversion:" + langversion)

    if debug:
        args.add("/debug+")
        args.add("/optimize-")
        args.add("/define:TRACE")
        args.add("/define:DEBUG")
    else:
        args.add("/debug-")
        args.add("/optimize+")
        args.add("/define:TRACE")
        args.add("/define:RELEASE")

    args.add("/debug:portable")

    # outputs
    if out_dll != None:
        args.add("/out:" + out_dll.path)
        args.add("/refout:" + out_ref.path)
        args.add("/pdb:" + out_pdb.path)
        outputs = [out_dll, out_ref, out_pdb]
    else:
        args.add("/refonly")
        args.add("/out:" + out_ref.path)
        outputs = [out_ref]

    if out_xml != None:
        args.add("/doc:" + out_xml.path)
        outputs.append(out_xml)

    # assembly references
    format_ref_arg(args, depset(framework_files, transitive = [refs]))

    # analyzers
    if run_analyzers:
        args.add_all(analyzer_assemblies, format_each = "/analyzer:%s")
        args.add_all(analyzer_assemblies_csharp, format_each = "/analyzer:%s")
        args.add_all(additionalfiles, format_each = "/additionalfile:%s")
        args.add_all(analyzer_configs, format_each = "/analyzerconfig:%s")

    # .cs files
    args.add_all(srcs)

    # resources
    args.add_all(resources, map_each = lambda r: map_resource_arg(r, label, out_dll.basename if out_dll != None else None, language = "csharp"), allow_closure = True)

    # defines
    args.add_all(defines, format_each = "/d:%s")

    # keyfile
    if keyfile != None:
        args.add("/keyfile:" + keyfile.path)

    # Additional compiler flags
    for option in compiler_options:
        args.add(option)

    # Source path remapping for debugger support (#228).
    # Maps user-specified path prefixes in PDB files so debuggers can
    # resolve source files without manual sourceFileMap configuration.
    # Note: the compiler wrapper already injects -pathmap:$PWD=. at
    # execution time for sandbox path remapping.
    for from_path, to_path in pathmap.items():
        args.add("/pathmap:" + from_path + "=" + to_path)

    # spill to a "response file" when the argument list gets too big (Bazel
    # makes that call based on limitations of the OS).
    args.set_param_file_format("multiline")

    args.use_param_file("@%s", use_always = True)

    direct_inputs = srcs + resources + additionalfiles + analyzer_configs + [toolchain.csharp_compiler.files_to_run.executable]
    direct_inputs += [keyfile] if keyfile else []

    # dotnet.exe csc.dll /noconfig <other csc args>
    # https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/command-line-building-with-csc-exe
    actions.run(
        mnemonic = "CSharpCompile",
        progress_message = "Compiling " + target_name + (" (internals ref-only dll)" if out_dll == None else ""),
        inputs = depset(
            direct = direct_inputs + framework_files + [compiler_wrapper, toolchain.runtime.files_to_run.executable],
            transitive = [refs, analyzer_assemblies, analyzer_assemblies_csharp, toolchain.runtime.default_runfiles.files, toolchain.csharp_compiler.default_runfiles.files, compile_data],
        ),
        outputs = outputs,
        executable = compiler_wrapper,
        arguments = [
            toolchain.runtime.files_to_run.executable.path,
            toolchain.csharp_compiler.files_to_run.executable.path,
            args,
        ],
        env = {
            "DOTNET_CLI_HOME": toolchain.runtime.files_to_run.executable.dirname,
        },
        toolchain = "//dotnet:toolchain_type",
    )
