"""NuGet package declarations for the parity test app.

Normally generated by paket2bazel. Hand-written here with the minimum
packages the parity app needs. Agents adding specs that require new
NuGet packages should add entries here and regenerate hashes.
"""

load("@rules_dotnet//dotnet:defs.bzl", "nuget_repo")

def parity():
    nuget_repo(
        name = "paket.parity",
        packages = [
            # --- spec-testing-infra (#207): NUnit test runner ---
            {
                "name": "NUnit",
                "id": "NUnit",
                "version": "4.5.1",
                "sha512": "sha512-cPf3kS8Z2P92cEFnQzrY/mlIWssVLdUPdGJ/J6QPLi1OQ/GShrUE0sDnGPxNBd9VzzZyEKlyRcG19NfMpmEngw==",
                "sources": ["https://api.nuget.org/v3/index.json"],
                "dependencies": {
                    "net6.0": [],
                    "net8.0": [],
                },
                "targeting_pack_overrides": [],
                "framework_list": [],
            },
            # --- spec-static-analysis (parity): Roslyn analyzer ---
            {
                "name": "StyleCop.Analyzers",
                "id": "StyleCop.Analyzers",
                "version": "1.2.0-beta.556",
                "sha512": "sha512-CBY/YGHrwm6puAaagun1ddZWpQ8dkpntqHT0EHcx6y4CtRLyAfHDTGmD2SuuzW7l6ZKqa2HHiulJCn/dvdUYgg==",
                "sources": ["https://api.nuget.org/v3/index.json"],
                "dependencies": {
                    "netstandard1.0": ["StyleCop.Analyzers.Unstable"],
                },
                "targeting_pack_overrides": [],
                "framework_list": [],
            },
            {
                "name": "StyleCop.Analyzers.Unstable",
                "id": "StyleCop.Analyzers.Unstable",
                "version": "1.2.0.556",
                "sha512": "sha512-Dp+65xPS0waQuzMecwimGYlO4mwTeYhV7AolKbMkaNZ/vPK8HwKqDzrn5oUdK1lWhO9BUkWqgRm5sbfVjDCRaw==",
                "sources": ["https://api.nuget.org/v3/index.json"],
                "dependencies": {
                    "netstandard1.0": [],
                },
                "targeting_pack_overrides": [],
                "framework_list": [],
            },
            # --- spec-proto-grpc (parity): protobuf runtime ---
            # csharp_proto_library auto-injects this, but it must exist in the repo.
            {
                "name": "Google.Protobuf",
                "id": "Google.Protobuf",
                "version": "3.34.0",
                "sha512": "sha512-xEr7lIhUrwsQqBV4b2SrOCjn+qDEwQv/LNCSM/OMrfD+gax19OK3TdAFgbCpAOeFhx6SNTIL8plajjejd0buPQ==",
                "sources": ["https://api.nuget.org/v3/index.json"],
                "dependencies": {
                    "net6.0": [],
                    "net8.0": [],
                },
                "targeting_pack_overrides": [],
                "framework_list": [],
            },
            # --- spec-proto-grpc (parity): gRPC core API (ClientBase, Marshaller, etc.) ---
            {
                "name": "Grpc.Core.Api",
                "id": "Grpc.Core.Api",
                "version": "2.70.0",
                "sha512": "sha512-EouQ/9+AoFEKXRuu4G1Axml3YcjpaKzNqjPC2LnFXJPFR7uY3AInvabxKUSqsKsNs+hmfiMCnJwi3bsN+VcMBw==",
                "sources": ["https://api.nuget.org/v3/index.json"],
                "dependencies": {
                    "net6.0": [],
                    "net8.0": [],
                    "netstandard2.1": [],
                },
                "targeting_pack_overrides": [],
                "framework_list": [],
            },
            # --- spec-proto-grpc (parity): gRPC runtime ---
            {
                "name": "Grpc.Tools",
                "id": "Grpc.Tools",
                "version": "2.70.0",
                "sha512": "sha512-4i4nIc9R74+bXjqHs7cTu7o6oir4YUMvc6/60eCVfakfZXwVifZUOpGMOFUcXfhIUc0I5ZE3KJPaPt4WHrhF7A==",
                "sources": ["https://api.nuget.org/v3/index.json"],
                "dependencies": {},
                "targeting_pack_overrides": [],
                "framework_list": [],
            },
        ],
    )
