"GENERATED BY SDK GENERATOR"

apphost_pack_lookup_table = {
    "netcoreapp3.0": {
        "linux-x64": "//dotnet/private/sdk/apphost_packs:netcoreapp3.0_linux-x64",
        "linux-arm64": "//dotnet/private/sdk/apphost_packs:netcoreapp3.0_linux-arm64",
        "osx-x64": "//dotnet/private/sdk/apphost_packs:netcoreapp3.0_osx-x64",
        "win-x64": "//dotnet/private/sdk/apphost_packs:netcoreapp3.0_win-x64",
        "win-arm64": "//dotnet/private/sdk/apphost_packs:netcoreapp3.0_win-arm64",
    },
    "netcoreapp3.1": {
        "linux-x64": "//dotnet/private/sdk/apphost_packs:netcoreapp3.1_linux-x64",
        "linux-arm64": "//dotnet/private/sdk/apphost_packs:netcoreapp3.1_linux-arm64",
        "osx-x64": "//dotnet/private/sdk/apphost_packs:netcoreapp3.1_osx-x64",
        "win-x64": "//dotnet/private/sdk/apphost_packs:netcoreapp3.1_win-x64",
        "win-arm64": "//dotnet/private/sdk/apphost_packs:netcoreapp3.1_win-arm64",
    },
    "net5.0": {
        "linux-x64": "//dotnet/private/sdk/apphost_packs:net5.0_linux-x64",
        "linux-arm64": "//dotnet/private/sdk/apphost_packs:net5.0_linux-arm64",
        "osx-x64": "//dotnet/private/sdk/apphost_packs:net5.0_osx-x64",
        "win-x64": "//dotnet/private/sdk/apphost_packs:net5.0_win-x64",
        "win-arm64": "//dotnet/private/sdk/apphost_packs:net5.0_win-arm64",
    },
    "net6.0": {
        "linux-x64": "//dotnet/private/sdk/apphost_packs:net6.0_linux-x64",
        "linux-arm64": "//dotnet/private/sdk/apphost_packs:net6.0_linux-arm64",
        "osx-x64": "//dotnet/private/sdk/apphost_packs:net6.0_osx-x64",
        "osx-arm64": "//dotnet/private/sdk/apphost_packs:net6.0_osx-arm64",
        "win-x64": "//dotnet/private/sdk/apphost_packs:net6.0_win-x64",
        "win-arm64": "//dotnet/private/sdk/apphost_packs:net6.0_win-arm64",
    },
    "net7.0": {
        "linux-x64": "//dotnet/private/sdk/apphost_packs:net7.0_linux-x64",
        "linux-arm64": "//dotnet/private/sdk/apphost_packs:net7.0_linux-arm64",
        "osx-x64": "//dotnet/private/sdk/apphost_packs:net7.0_osx-x64",
        "osx-arm64": "//dotnet/private/sdk/apphost_packs:net7.0_osx-arm64",
        "win-x64": "//dotnet/private/sdk/apphost_packs:net7.0_win-x64",
        "win-arm64": "//dotnet/private/sdk/apphost_packs:net7.0_win-arm64",
    },
    "net8.0": {
        "linux-x64": "//dotnet/private/sdk/apphost_packs:net8.0_linux-x64",
        "linux-arm64": "//dotnet/private/sdk/apphost_packs:net8.0_linux-arm64",
        "osx-x64": "//dotnet/private/sdk/apphost_packs:net8.0_osx-x64",
        "osx-arm64": "//dotnet/private/sdk/apphost_packs:net8.0_osx-arm64",
        "win-x64": "//dotnet/private/sdk/apphost_packs:net8.0_win-x64",
        "win-arm64": "//dotnet/private/sdk/apphost_packs:net8.0_win-arm64",
    },
}
